name: k8s image sync
on:
  schedule:
  - cron: 0 */6 * * *
jobs:
  k8s-image-sync:
    name: k8s image sync
    runs-on: ubuntu-latest
    steps:
    - name: sync
      uses: maguowei/actions/k8s-image-sync@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gotok8s
  github-package-k8s-image-sync:
    name: github package k8s image sync
    runs-on: ubuntu-latest
    steps:
    - name: sync
      uses: maguowei/actions/k8s-image-sync@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        repository: gotok8s/gotok8s
